import = ["/home/daniil/.config/alacritty/catppuccin-mocha.toml", "/home/daniil/.config/alacritty/fonts.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[shell]
program = "zsh"

[window]
decorations = "none"
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 240
lines = 160
[window.padding]
x = 12
y = 12
